apiVersion: apps/v1
kind: Deployment
metadata:
  name: apprmq
  labels:
    app: apprmq
spec:
  selector:
    matchLabels:
      app: apprmq
  replicas: 1
  template:
    metadata:
      labels:
        app: apprmq
    spec:
      containers:
        - name: apprmq
          image: rabbitmq
          ports:
            - name: apprmq-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom: 
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"      
       